#!/usr/bin/expect

log_user 1

set timeout 3
set tmp_file "./test.txt"

send "touch aaaaa\n"
# expect "touch" {puts "touch detect!!!!"}

# spawn touch aaaaa
# spawn ls -l
# expect "aaaaa" {puts "find strings!!!"}

# spawn find  ./ -type f
# expect "ttttt" {puts "find!!!!"}

spawn sh -c "echo pc-kira > ./tmp.txt"
spawn cat ./tmp.txt
expect { 
    "pc-kira" {puts "hit!!!"}
    default {puts "non-hit!!!"}
}

puts "test strings2."

exit
